// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $blog from "./routes/blog.tsx";
import * as $devs_michael_index from "./routes/devs/michael/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $set_title_index from "./islands/set-title/index.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/blog.tsx": $blog,
    "./routes/devs/michael/index.tsx": $devs_michael_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/set-title/index.tsx": $set_title_index,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
